<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.DB.HZone.Tests" Version="29.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\CK.DB.HWorkspace.Page\CK.DB.HWorkspace.Page.csproj" />
    <ProjectReference Include="..\CK.DB.HWorkspace.Tests\CK.DB.HWorkspace.Tests.csproj" />
    <ProjectReference Include="..\CK.DB.Workspace.Page.Tests\CK.DB.Workspace.Page.Tests.csproj" />
  </ItemGroup>
</Project>