<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.DB.HZone" Version="28.0.0--ci.5" />
    <PackageReference Include="CK.DB.Workspace" Version="15.0.0--ci.7" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="**\*.sql;**\*.tql;**\*.y4" Exclude="bin\**;obj\**;CodeCakeBuilder\**;packages\**;@(EmbeddedResource)" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Res\**\*.sql" />
    <None Remove="Res\**\*.tql" />
  </ItemGroup>
</Project>